TOP=../../..
include $(TOP)/configure/CONFIG
#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE

#----------------------------------------------------
#  Optimization of db files using dbst (DEFAULT: NO)
#DB_OPT = YES

#----------------------------------------------------
# Create and install (or just install)
# databases, templates, substitutions like this
#
# EVR databases
DB += evr.db
DB += evrWithDelays.db
DB += evrWithExtDelays.db
DB += evrWithFrontPanel.db
DB += evrPmc.db
DB += evrWithDelaysPmc.db
DB += evrWithExtDelaysPmc.db
DB += evrWithFrontPanelPmc.db

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE

